#docker-compose.yml
services:
  # -------------------------
  # MinIO : Stockage objets S3
  # -------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 3

  # -------------------------
  # MLflow : Model Registry
  # -------------------------
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    depends_on:
      - minio
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    command: >
      mlflow server
      --backend-store-uri /app/mlruns
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000

    ports:
      - "5001:5000"

  # -------------------------
  # API : FastAPI
  # -------------------------
  api:
    build: ./src/api
    container_name: api
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - "8000:8000"

  # -------------------------
  # Front : Streamlit
  # -------------------------
  front:
    build: ./src/front
    container_name: front
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      API_URL: http://api:8000

  train:
    build: ./src/train
    container_name: train
    depends_on:
      - mlflow
      - minio
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5001
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    

# -------------------------
# Volumes persistants
# -------------------------
volumes:
  minio-data:
  mlruns: